# Generated by Django 3.0.3 on 2020-08-04 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='is_active',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
